# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nhakkaou <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/03 18:43:37 by nhakkaou          #+#    #+#              #
#    Updated: 2018/10/03 21:34:42 by nhakkaou         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all :
	gcc -Wall -Wextra -Werror includes/*.h srcs/*.c
	mv a.out ft_display_file
clean :
	rm -f srcs/*.o
	rm -f includes/*.gch
fclean : clean
	rm ft_display_file
